import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider";
import { Suspense } from "react";
import BottomNavigationBar from "@/components/BottomNavigationBar";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="md:max-w-md bg-white md:m-auto">
      <body className={inter.className}>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_APP_KEY}&autoload=false&libraries=services`}
          strategy="beforeInteractive"
        />
        <Provider>
          <div className="  bg-white md:drop-shadow-2xl ">
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
            <BottomNavigationBar />
          </div>
        </Provider>
      </body>
    </html>
  );
}
